# Generated by Django 4.2.6 on 2023-10-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='development_field',
            field=models.CharField(max_length=50),
        ),
    ]
