# Generated by Django 4.2.6 on 2023-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_post',
            name='title',
            field=models.CharField(error_messages={'required': '제목을 입력해주세요.'}, max_length=100),
        ),
    ]
