# Generated by Django 4.2.6 on 2023-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='board_post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
