# Generated by Django 4.2.6 on 2023-11-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_post_content_alter_board_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Board_Image',
        ),
    ]
