# Generated by Django 4.2.6 on 2023-11-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_post_content_delete_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_post',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='board_post',
            name='content',
            field=models.TextField(),
        ),
    ]
